### PR TITLE
Applied the changes which were missed in https://github.com/easylogic/codemirror-colorpicker/commit/00dc98423bddb29f9540b15a229f52b44fc12452

### PR DESCRIPTION
**Pull request by webextensions**

### CODE REVIEW

**Comment by easylogic** [comment]
hi @webextensions   

Thanks for your PR. 

But your code is already applied  in master branch. 

refer to  https://github.com/easylogic/codemirror-colorpicker/blob/ebdca295f56bdbf4afa5dc079e3026a410d97f52/src/extension/codemirror/colorview.js#L388-L406

**Comment by webextensions** [comment]
@easylogic
I am looking to include it from https://raw.githubusercontent.com/easylogic/codemirror-colorpicker/v1.9.51/addon/colorpicker/colorview.js (via master branch or appropriate tag) since it can be added on top of CodeMirror of my project and doesn't need any build system.

**Comment by easylogic** [comment]
ok, i understood.

**Comment by easylogic** [comment]
please see to https://raw.githubusercontent.com/easylogic/codemirror-colorpicker/v1.9.52/addon/colorpicker/colorview.js

**Pull request merged**
